base_url = "https://ardus.cargill.ie"

title = "Ardus"
Description = """A campaign setting for D&D 5e"""

compile_sass = true
highlight_code = false
build_search_index = true

theme = "book"

[extra]
book_numbered_chapters = false
